// GENERATED by packages/data/scripts/import-from-pokerogue.mjs — do not hand-edit.
// Re-run the script against a poke_the_spire checkout to refresh the ability list.

/**
 * Reference-only ability data (id/name + the PokeRogue attr-class names it applies,
 * as a lightweight tag list). Ability *effects* are not simulated by the engine —
 * see TODO.md. No plain-text ability descriptions ship in this source tree (they
 * live in a separate i18n locale repo PokeRogue didn't have checked out here), so
 * "description" is intentionally absent; the tag list is the closest at-a-glance
 * summary available without porting each attr's battle logic.
 */
export interface AbilityDexEntry {
  id: number;
  key: string;
  name: string;
  /** PokeRogue AbAttr class names this ability applies — a tag list, not implemented logic. */
  tags: string[];
  /** True if the ability is suppressible by Mold Breaker-style effects (PokeRogue's `.ignorable()`). */
  ignorable: boolean;
}

export const ABILITY_DEX: AbilityDexEntry[] = [
  {
    id: 0,
    key: "NONE",
    name: "None",
    tags: [],
    ignorable: false
  },
  {
    id: 1,
    key: "STENCH",
    name: "Stench",
    tags: [
      "PostAttackApplyBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 2,
    key: "DRIZZLE",
    name: "Drizzle",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 3,
    key: "SPEED_BOOST",
    name: "Speed Boost",
    tags: [
      "SpeedBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 4,
    key: "BATTLE_ARMOR",
    name: "Battle Armor",
    tags: [
      "BlockCritAbAttr"
    ],
    ignorable: true
  },
  {
    id: 5,
    key: "STURDY",
    name: "Sturdy",
    tags: [
      "PreDefendFullHpEndureAbAttr",
      "BlockOneHitKOAbAttr"
    ],
    ignorable: true
  },
  {
    id: 6,
    key: "DAMP",
    name: "Damp",
    tags: [
      "FieldPreventExplosiveMovesAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: true
  },
  {
    id: 7,
    key: "LIMBER",
    name: "Limber",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 8,
    key: "SAND_VEIL",
    name: "Sand Veil",
    tags: [
      "StatMultiplierAbAttr",
      "BlockWeatherDamageAttr"
    ],
    ignorable: true
  },
  {
    id: 9,
    key: "STATIC",
    name: "Static",
    tags: [
      "PostDefendApplyStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 10,
    key: "VOLT_ABSORB",
    name: "Volt Absorb",
    tags: [
      "TypeImmunityHealAbAttr"
    ],
    ignorable: true
  },
  {
    id: 11,
    key: "WATER_ABSORB",
    name: "Water Absorb",
    tags: [
      "TypeImmunityHealAbAttr"
    ],
    ignorable: true
  },
  {
    id: 12,
    key: "OBLIVIOUS",
    name: "Oblivious",
    tags: [
      "BattlerTagImmunityAbAttr",
      "PostSummonRemoveBattlerTagAbAttr",
      "IntimidateImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 13,
    key: "CLOUD_NINE",
    name: "Cloud Nine",
    tags: [
      "SuppressWeatherEffectAbAttr",
      "PostSummonUnnamedMessageAbAttr",
      "PostSummonWeatherSuppressedFormChangeAbAttr",
      "PostFaintUnsuppressedWeatherFormChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 14,
    key: "COMPOUND_EYES",
    name: "Compound Eyes",
    tags: [
      "StatMultiplierAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 15,
    key: "INSOMNIA",
    name: "Insomnia",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr",
      "BattlerTagImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 16,
    key: "COLOR_CHANGE",
    name: "Color Change",
    tags: [
      "PostDefendTypeChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 17,
    key: "IMMUNITY",
    name: "Immunity",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 18,
    key: "FLASH_FIRE",
    name: "Flash Fire",
    tags: [
      "TypeImmunityAddBattlerTagAbAttr"
    ],
    ignorable: true
  },
  {
    id: 19,
    key: "SHIELD_DUST",
    name: "Shield Dust",
    tags: [
      "IgnoreMoveEffectsAbAttr"
    ],
    ignorable: true
  },
  {
    id: 20,
    key: "OWN_TEMPO",
    name: "Own Tempo",
    tags: [
      "BattlerTagImmunityAbAttr",
      "PostSummonRemoveBattlerTagAbAttr",
      "IntimidateImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 21,
    key: "SUCTION_CUPS",
    name: "Suction Cups",
    tags: [
      "ForceSwitchOutImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 22,
    key: "INTIMIDATE",
    name: "Intimidate",
    tags: [
      "PostSummonStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 23,
    key: "SHADOW_TAG",
    name: "Shadow Tag",
    tags: [
      "ArenaTrapAbAttr"
    ],
    ignorable: false
  },
  {
    id: 24,
    key: "ROUGH_SKIN",
    name: "Rough Skin",
    tags: [
      "PostDefendContactDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 25,
    key: "WONDER_GUARD",
    name: "Wonder Guard",
    tags: [
      "NonSuperEffectiveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 26,
    key: "LEVITATE",
    name: "Levitate",
    tags: [
      "AttackTypeImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 27,
    key: "EFFECT_SPORE",
    name: "Effect Spore",
    tags: [
      "EffectSporeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 28,
    key: "SYNCHRONIZE",
    name: "Synchronize",
    tags: [
      "SyncEncounterNatureAbAttr",
      "SynchronizeStatusAbAttr"
    ],
    ignorable: false
  },
  {
    id: 29,
    key: "CLEAR_BODY",
    name: "Clear Body",
    tags: [
      "ProtectStatAbAttr"
    ],
    ignorable: true
  },
  {
    id: 30,
    key: "NATURAL_CURE",
    name: "Natural Cure",
    tags: [
      "PreSwitchOutResetStatusAbAttr"
    ],
    ignorable: false
  },
  {
    id: 31,
    key: "LIGHTNING_ROD",
    name: "Lightning Rod",
    tags: [
      "RedirectTypeMoveAbAttr",
      "TypeImmunityStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 32,
    key: "SERENE_GRACE",
    name: "Serene Grace",
    tags: [
      "MoveEffectChanceMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 33,
    key: "SWIFT_SWIM",
    name: "Swift Swim",
    tags: [
      "StatMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 34,
    key: "CHLOROPHYLL",
    name: "Chlorophyll",
    tags: [
      "StatMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 35,
    key: "ILLUMINATE",
    name: "Illuminate",
    tags: [
      "ProtectStatAbAttr",
      "DoubleBattleChanceAbAttr",
      "IgnoreOpponentStatStagesAbAttr"
    ],
    ignorable: true
  },
  {
    id: 36,
    key: "TRACE",
    name: "Trace",
    tags: [
      "PostSummonCopyAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 37,
    key: "HUGE_POWER",
    name: "Huge Power",
    tags: [
      "StatMultiplierAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 38,
    key: "POISON_POINT",
    name: "Poison Point",
    tags: [
      "PostDefendApplyStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 39,
    key: "INNER_FOCUS",
    name: "Inner Focus",
    tags: [
      "BattlerTagImmunityAbAttr",
      "IntimidateImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 40,
    key: "MAGMA_ARMOR",
    name: "Magma Armor",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 41,
    key: "WATER_VEIL",
    name: "Water Veil",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 42,
    key: "MAGNET_PULL",
    name: "Magnet Pull",
    tags: [
      "ArenaTrapAbAttr"
    ],
    ignorable: false
  },
  {
    id: 43,
    key: "SOUNDPROOF",
    name: "Soundproof",
    tags: [
      "MoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 44,
    key: "RAIN_DISH",
    name: "Rain Dish",
    tags: [
      "PostWeatherLapseHealAbAttr"
    ],
    ignorable: false
  },
  {
    id: 45,
    key: "SAND_STREAM",
    name: "Sand Stream",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 46,
    key: "PRESSURE",
    name: "Pressure",
    tags: [
      "IncreasePpUsedAbAttr",
      "PostSummonMessageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 47,
    key: "THICK_FAT",
    name: "Thick Fat",
    tags: [
      "ReceivedTypeDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 48,
    key: "EARLY_BIRD",
    name: "Early Bird",
    tags: [
      "ReduceStatusEffectDurationAbAttr"
    ],
    ignorable: false
  },
  {
    id: 49,
    key: "FLAME_BODY",
    name: "Flame Body",
    tags: [
      "PostDefendApplyStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 50,
    key: "RUN_AWAY",
    name: "Run Away",
    tags: [
      "RunSuccessAbAttr"
    ],
    ignorable: false
  },
  {
    id: 51,
    key: "KEEN_EYE",
    name: "Keen Eye",
    tags: [
      "ProtectStatAbAttr",
      "IgnoreOpponentStatStagesAbAttr"
    ],
    ignorable: true
  },
  {
    id: 52,
    key: "HYPER_CUTTER",
    name: "Hyper Cutter",
    tags: [
      "ProtectStatAbAttr"
    ],
    ignorable: true
  },
  {
    id: 53,
    key: "PICKUP",
    name: "Pickup",
    tags: [
      "PostBattleLootAbAttr"
    ],
    ignorable: false
  },
  {
    id: 54,
    key: "TRUANT",
    name: "Truant",
    tags: [
      "PostSummonAddBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 55,
    key: "HUSTLE",
    name: "Hustle",
    tags: [
      "StatMultiplierAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 56,
    key: "CUTE_CHARM",
    name: "Cute Charm",
    tags: [
      "PostDefendContactApplyTagChanceAbAttr"
    ],
    ignorable: false
  },
  {
    id: 57,
    key: "PLUS",
    name: "Plus",
    tags: [],
    ignorable: false
  },
  {
    id: 58,
    key: "MINUS",
    name: "Minus",
    tags: [],
    ignorable: false
  },
  {
    id: 59,
    key: "FORECAST",
    name: "Forecast",
    tags: [
      "NoFusionAbilityAbAttr",
      "PostSummonFormChangeByWeatherAbAttr",
      "PostWeatherChangeFormChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 60,
    key: "STICKY_HOLD",
    name: "Sticky Hold",
    tags: [
      "BlockItemTheftAbAttr"
    ],
    ignorable: true
  },
  {
    id: 61,
    key: "SHED_SKIN",
    name: "Shed Skin",
    tags: [],
    ignorable: false
  },
  {
    id: 62,
    key: "GUTS",
    name: "Guts",
    tags: [
      "BypassBurnDamageReductionAbAttr"
    ],
    ignorable: false
  },
  {
    id: 63,
    key: "MARVEL_SCALE",
    name: "Marvel Scale",
    tags: [],
    ignorable: true
  },
  {
    id: 64,
    key: "LIQUID_OOZE",
    name: "Liquid Ooze",
    tags: [
      "ReverseDrainAbAttr"
    ],
    ignorable: false
  },
  {
    id: 65,
    key: "OVERGROW",
    name: "Overgrow",
    tags: [
      "LowHpMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 66,
    key: "BLAZE",
    name: "Blaze",
    tags: [
      "LowHpMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 67,
    key: "TORRENT",
    name: "Torrent",
    tags: [
      "LowHpMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 68,
    key: "SWARM",
    name: "Swarm",
    tags: [
      "LowHpMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 69,
    key: "ROCK_HEAD",
    name: "Rock Head",
    tags: [
      "BlockRecoilDamageAttr"
    ],
    ignorable: false
  },
  {
    id: 70,
    key: "DROUGHT",
    name: "Drought",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 71,
    key: "ARENA_TRAP",
    name: "Arena Trap",
    tags: [
      "ArenaTrapAbAttr",
      "DoubleBattleChanceAbAttr"
    ],
    ignorable: false
  },
  {
    id: 72,
    key: "VITAL_SPIRIT",
    name: "Vital Spirit",
    tags: [
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr",
      "BattlerTagImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 73,
    key: "WHITE_SMOKE",
    name: "White Smoke",
    tags: [
      "ProtectStatAbAttr"
    ],
    ignorable: true
  },
  {
    id: 74,
    key: "PURE_POWER",
    name: "Pure Power",
    tags: [
      "StatMultiplierAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 75,
    key: "SHELL_ARMOR",
    name: "Shell Armor",
    tags: [
      "BlockCritAbAttr"
    ],
    ignorable: true
  },
  {
    id: 76,
    key: "AIR_LOCK",
    name: "Air Lock",
    tags: [
      "SuppressWeatherEffectAbAttr",
      "PostSummonUnnamedMessageAbAttr",
      "PostSummonWeatherSuppressedFormChangeAbAttr",
      "PostFaintUnsuppressedWeatherFormChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 77,
    key: "TANGLED_FEET",
    name: "Tangled Feet",
    tags: [],
    ignorable: true
  },
  {
    id: 78,
    key: "MOTOR_DRIVE",
    name: "Motor Drive",
    tags: [
      "TypeImmunityStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 79,
    key: "RIVALRY",
    name: "Rivalry",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 80,
    key: "STEADFAST",
    name: "Steadfast",
    tags: [
      "FlinchStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 81,
    key: "SNOW_CLOAK",
    name: "Snow Cloak",
    tags: [
      "StatMultiplierAbAttr",
      "BlockWeatherDamageAttr"
    ],
    ignorable: true
  },
  {
    id: 82,
    key: "GLUTTONY",
    name: "Gluttony",
    tags: [
      "ReduceBerryUseThresholdAbAttr"
    ],
    ignorable: false
  },
  {
    id: 83,
    key: "ANGER_POINT",
    name: "Anger Point",
    tags: [
      "PostReceiveCritStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 84,
    key: "UNBURDEN",
    name: "Unburden",
    tags: [
      "PostItemLostApplyBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 85,
    key: "HEATPROOF",
    name: "Heatproof",
    tags: [
      "ReceivedTypeDamageMultiplierAbAttr",
      "ReduceBurnDamageAbAttr"
    ],
    ignorable: true
  },
  {
    id: 86,
    key: "SIMPLE",
    name: "Simple",
    tags: [
      "StatStageChangeMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 87,
    key: "DRY_SKIN",
    name: "Dry Skin",
    tags: [
      "PostWeatherLapseDamageAbAttr",
      "PostWeatherLapseHealAbAttr",
      "ReceivedTypeDamageMultiplierAbAttr",
      "TypeImmunityHealAbAttr"
    ],
    ignorable: true
  },
  {
    id: 88,
    key: "DOWNLOAD",
    name: "Download",
    tags: [
      "DownloadAbAttr"
    ],
    ignorable: false
  },
  {
    id: 89,
    key: "IRON_FIST",
    name: "Iron Fist",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 90,
    key: "POISON_HEAL",
    name: "Poison Heal",
    tags: [
      "PostTurnStatusHealAbAttr",
      "BlockStatusDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 91,
    key: "ADAPTABILITY",
    name: "Adaptability",
    tags: [
      "StabBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 92,
    key: "SKILL_LINK",
    name: "Skill Link",
    tags: [
      "MaxMultiHitAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 93,
    key: "HYDRATION",
    name: "Hydration",
    tags: [
      "PostTurnResetStatusAbAttr"
    ],
    ignorable: false
  },
  {
    id: 94,
    key: "SOLAR_POWER",
    name: "Solar Power",
    tags: [
      "PostWeatherLapseDamageAbAttr",
      "StatMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 95,
    key: "QUICK_FEET",
    name: "Quick Feet",
    tags: [],
    ignorable: false
  },
  {
    id: 96,
    key: "NORMALIZE",
    name: "Normalize",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 97,
    key: "SNIPER",
    name: "Sniper",
    tags: [
      "MultCritAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 98,
    key: "MAGIC_GUARD",
    name: "Magic Guard",
    tags: [
      "BlockNonDirectDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 99,
    key: "NO_GUARD",
    name: "No Guard",
    tags: [
      "AlwaysHitAbAttr",
      "DoubleBattleChanceAbAttr"
    ],
    ignorable: false
  },
  {
    id: 100,
    key: "STALL",
    name: "Stall",
    tags: [
      "ChangeMovePriorityInBracketAbAttr"
    ],
    ignorable: false
  },
  {
    id: 101,
    key: "TECHNICIAN",
    name: "Technician",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 102,
    key: "LEAF_GUARD",
    name: "Leaf Guard",
    tags: [
      "StatusEffectImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 103,
    key: "KLUTZ",
    name: "Klutz",
    tags: [],
    ignorable: false
  },
  {
    id: 104,
    key: "MOLD_BREAKER",
    name: "Mold Breaker",
    tags: [
      "PostSummonMessageAbAttr",
      "MoveAbilityBypassAbAttr"
    ],
    ignorable: false
  },
  {
    id: 105,
    key: "SUPER_LUCK",
    name: "Super Luck",
    tags: [
      "BonusCritAbAttr"
    ],
    ignorable: false
  },
  {
    id: 106,
    key: "AFTERMATH",
    name: "Aftermath",
    tags: [
      "PostFaintContactDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 107,
    key: "ANTICIPATION",
    name: "Anticipation",
    tags: [],
    ignorable: false
  },
  {
    id: 108,
    key: "FOREWARN",
    name: "Forewarn",
    tags: [
      "ForewarnAbAttr"
    ],
    ignorable: false
  },
  {
    id: 109,
    key: "UNAWARE",
    name: "Unaware",
    tags: [
      "IgnoreOpponentStatStagesAbAttr"
    ],
    ignorable: true
  },
  {
    id: 110,
    key: "TINTED_LENS",
    name: "Tinted Lens",
    tags: [
      "MoveDamageBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 111,
    key: "FILTER",
    name: "Filter",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 112,
    key: "SLOW_START",
    name: "Slow Start",
    tags: [
      "PostSummonAddBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 113,
    key: "SCRAPPY",
    name: "Scrappy",
    tags: [
      "IgnoreTypeImmunityAbAttr",
      "IntimidateImmunityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 114,
    key: "STORM_DRAIN",
    name: "Storm Drain",
    tags: [
      "RedirectTypeMoveAbAttr",
      "TypeImmunityStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 115,
    key: "ICE_BODY",
    name: "Ice Body",
    tags: [
      "BlockWeatherDamageAttr",
      "PostWeatherLapseHealAbAttr"
    ],
    ignorable: false
  },
  {
    id: 116,
    key: "SOLID_ROCK",
    name: "Solid Rock",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 117,
    key: "SNOW_WARNING",
    name: "Snow Warning",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 118,
    key: "HONEY_GATHER",
    name: "Honey Gather",
    tags: [
      "MoneyAbAttr"
    ],
    ignorable: false
  },
  {
    id: 119,
    key: "FRISK",
    name: "Frisk",
    tags: [
      "FriskAbAttr"
    ],
    ignorable: false
  },
  {
    id: 120,
    key: "RECKLESS",
    name: "Reckless",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 121,
    key: "MULTITYPE",
    name: "Multitype",
    tags: [
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 122,
    key: "FLOWER_GIFT",
    name: "Flower Gift",
    tags: [
      "NoFusionAbilityAbAttr",
      "PostSummonFormChangeByWeatherAbAttr",
      "PostWeatherChangeFormChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 123,
    key: "BAD_DREAMS",
    name: "Bad Dreams",
    tags: [
      "PostTurnHurtIfSleepingAbAttr"
    ],
    ignorable: false
  },
  {
    id: 124,
    key: "PICKPOCKET",
    name: "Pickpocket",
    tags: [
      "PostDefendStealHeldItemAbAttr"
    ],
    ignorable: false
  },
  {
    id: 125,
    key: "SHEER_FORCE",
    name: "Sheer Force",
    tags: [
      "MovePowerBoostAbAttr",
      "MoveEffectChanceMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 126,
    key: "CONTRARY",
    name: "Contrary",
    tags: [
      "StatStageChangeMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 127,
    key: "UNNERVE",
    name: "Unnerve",
    tags: [
      "PreventBerryUseAbAttr"
    ],
    ignorable: false
  },
  {
    id: 128,
    key: "DEFIANT",
    name: "Defiant",
    tags: [
      "PostStatStageChangeStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 129,
    key: "DEFEATIST",
    name: "Defeatist",
    tags: [
      "StatMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 130,
    key: "CURSED_BODY",
    name: "Cursed Body",
    tags: [
      "PostDefendMoveDisableAbAttr"
    ],
    ignorable: false
  },
  {
    id: 131,
    key: "HEALER",
    name: "Healer",
    tags: [],
    ignorable: false
  },
  {
    id: 132,
    key: "FRIEND_GUARD",
    name: "Friend Guard",
    tags: [
      "AlliedFieldDamageReductionAbAttr"
    ],
    ignorable: true
  },
  {
    id: 133,
    key: "WEAK_ARMOR",
    name: "Weak Armor",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 134,
    key: "HEAVY_METAL",
    name: "Heavy Metal",
    tags: [
      "WeightMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 135,
    key: "LIGHT_METAL",
    name: "Light Metal",
    tags: [
      "WeightMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 136,
    key: "MULTISCALE",
    name: "Multiscale",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 137,
    key: "TOXIC_BOOST",
    name: "Toxic Boost",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 138,
    key: "FLARE_BOOST",
    name: "Flare Boost",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 139,
    key: "HARVEST",
    name: "Harvest",
    tags: [
      "PostTurnRestoreBerryAbAttr"
    ],
    ignorable: false
  },
  {
    id: 140,
    key: "TELEPATHY",
    name: "Telepathy",
    tags: [
      "MoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 141,
    key: "MOODY",
    name: "Moody",
    tags: [
      "MoodyAbAttr"
    ],
    ignorable: false
  },
  {
    id: 142,
    key: "OVERCOAT",
    name: "Overcoat",
    tags: [
      "BlockWeatherDamageAttr",
      "MoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 143,
    key: "POISON_TOUCH",
    name: "Poison Touch",
    tags: [
      "PostAttackContactApplyStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 144,
    key: "REGENERATOR",
    name: "Regenerator",
    tags: [
      "PreSwitchOutHealAbAttr"
    ],
    ignorable: false
  },
  {
    id: 145,
    key: "BIG_PECKS",
    name: "Big Pecks",
    tags: [
      "ProtectStatAbAttr"
    ],
    ignorable: true
  },
  {
    id: 146,
    key: "SAND_RUSH",
    name: "Sand Rush",
    tags: [
      "StatMultiplierAbAttr",
      "BlockWeatherDamageAttr"
    ],
    ignorable: false
  },
  {
    id: 147,
    key: "WONDER_SKIN",
    name: "Wonder Skin",
    tags: [
      "WonderSkinAbAttr"
    ],
    ignorable: true
  },
  {
    id: 148,
    key: "ANALYTIC",
    name: "Analytic",
    tags: [
      "MovePowerBoostAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 149,
    key: "ILLUSION",
    name: "Illusion",
    tags: [
      "IllusionPreSummonAbAttr",
      "IllusionBreakAbAttr",
      "PostDefendIllusionBreakAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 150,
    key: "IMPOSTER",
    name: "Imposter",
    tags: [
      "PostSummonTransformAbAttr"
    ],
    ignorable: false
  },
  {
    id: 151,
    key: "INFILTRATOR",
    name: "Infiltrator",
    tags: [
      "InfiltratorAbAttr"
    ],
    ignorable: false
  },
  {
    id: 152,
    key: "MUMMY",
    name: "Mummy",
    tags: [
      "PostDefendAbilityGiveAbAttr"
    ],
    ignorable: false
  },
  {
    id: 153,
    key: "MOXIE",
    name: "Moxie",
    tags: [
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 154,
    key: "JUSTIFIED",
    name: "Justified",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 155,
    key: "RATTLED",
    name: "Rattled",
    tags: [
      "PostDefendStatStageChangeAbAttr",
      "PostIntimidateStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 156,
    key: "MAGIC_BOUNCE",
    name: "Magic Bounce",
    tags: [
      "ReflectStatusMoveAbAttr"
    ],
    ignorable: true
  },
  {
    id: 157,
    key: "SAP_SIPPER",
    name: "Sap Sipper",
    tags: [
      "TypeImmunityStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 158,
    key: "PRANKSTER",
    name: "Prankster",
    tags: [
      "ChangeMovePriorityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 159,
    key: "SAND_FORCE",
    name: "Sand Force",
    tags: [
      "MoveTypePowerBoostAbAttr",
      "BlockWeatherDamageAttr"
    ],
    ignorable: false
  },
  {
    id: 160,
    key: "IRON_BARBS",
    name: "Iron Barbs",
    tags: [
      "PostDefendContactDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 161,
    key: "ZEN_MODE",
    name: "Zen Mode",
    tags: [
      "PostBattleInitFormChangeAbAttr",
      "PostSummonFormChangeAbAttr",
      "PostTurnFormChangeAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 162,
    key: "VICTORY_STAR",
    name: "Victory Star",
    tags: [
      "StatMultiplierAbAttr",
      "AllyStatMultiplierAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 163,
    key: "TURBOBLAZE",
    name: "Turboblaze",
    tags: [
      "PostSummonMessageAbAttr",
      "MoveAbilityBypassAbAttr"
    ],
    ignorable: false
  },
  {
    id: 164,
    key: "TERAVOLT",
    name: "Teravolt",
    tags: [
      "PostSummonMessageAbAttr",
      "MoveAbilityBypassAbAttr"
    ],
    ignorable: false
  },
  {
    id: 165,
    key: "AROMA_VEIL",
    name: "Aroma Veil",
    tags: [
      "UserFieldBattlerTagImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 166,
    key: "FLOWER_VEIL",
    name: "Flower Veil",
    tags: [
      "ConditionalUserFieldStatusEffectImmunityAbAttr",
      "ConditionalUserFieldBattlerTagImmunityAbAttr",
      "ConditionalUserFieldProtectStatAbAttr"
    ],
    ignorable: true
  },
  {
    id: 167,
    key: "CHEEK_POUCH",
    name: "Cheek Pouch",
    tags: [
      "HealFromBerryUseAbAttr"
    ],
    ignorable: false
  },
  {
    id: 168,
    key: "PROTEAN",
    name: "Protean",
    tags: [
      "PokemonTypeChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 169,
    key: "FUR_COAT",
    name: "Fur Coat",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 170,
    key: "MAGICIAN",
    name: "Magician",
    tags: [
      "PostAttackStealHeldItemAbAttr"
    ],
    ignorable: false
  },
  {
    id: 171,
    key: "BULLETPROOF",
    name: "Bulletproof",
    tags: [
      "MoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 172,
    key: "COMPETITIVE",
    name: "Competitive",
    tags: [
      "PostStatStageChangeStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 173,
    key: "STRONG_JAW",
    name: "Strong Jaw",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 174,
    key: "REFRIGERATE",
    name: "Refrigerate",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 175,
    key: "SWEET_VEIL",
    name: "Sweet Veil",
    tags: [
      "UserFieldStatusEffectImmunityAbAttr",
      "PostSummonUserFieldRemoveStatusEffectAbAttr",
      "UserFieldBattlerTagImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 176,
    key: "STANCE_CHANGE",
    name: "Stance Change",
    tags: [
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 177,
    key: "GALE_WINGS",
    name: "Gale Wings",
    tags: [
      "ChangeMovePriorityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 178,
    key: "MEGA_LAUNCHER",
    name: "Mega Launcher",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 179,
    key: "GRASS_PELT",
    name: "Grass Pelt",
    tags: [],
    ignorable: true
  },
  {
    id: 180,
    key: "SYMBIOSIS",
    name: "Symbiosis",
    tags: [],
    ignorable: false
  },
  {
    id: 181,
    key: "TOUGH_CLAWS",
    name: "Tough Claws",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 182,
    key: "PIXILATE",
    name: "Pixilate",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 183,
    key: "GOOEY",
    name: "Gooey",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 184,
    key: "AERILATE",
    name: "Aerilate",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 185,
    key: "PARENTAL_BOND",
    name: "Parental Bond",
    tags: [
      "AddSecondStrikeAbAttr",
      "MoveDamageBoostAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 186,
    key: "DARK_AURA",
    name: "Dark Aura",
    tags: [
      "PostSummonMessageAbAttr",
      "FieldMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 187,
    key: "FAIRY_AURA",
    name: "Fairy Aura",
    tags: [
      "PostSummonMessageAbAttr",
      "FieldMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 188,
    key: "AURA_BREAK",
    name: "Aura Break",
    tags: [],
    ignorable: true
  },
  {
    id: 189,
    key: "PRIMORDIAL_SEA",
    name: "Primordial Sea",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "PreLeaveFieldClearWeatherAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 190,
    key: "DESOLATE_LAND",
    name: "Desolate Land",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "PreLeaveFieldClearWeatherAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 191,
    key: "DELTA_STREAM",
    name: "Delta Stream",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "PreLeaveFieldClearWeatherAbAttr"
    ],
    ignorable: false
  },
  {
    id: 192,
    key: "STAMINA",
    name: "Stamina",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 193,
    key: "WIMP_OUT",
    name: "Wimp Out",
    tags: [
      "PostDamageForceSwitchAbAttr"
    ],
    ignorable: false
  },
  {
    id: 194,
    key: "EMERGENCY_EXIT",
    name: "Emergency Exit",
    tags: [
      "PostDamageForceSwitchAbAttr"
    ],
    ignorable: false
  },
  {
    id: 195,
    key: "WATER_COMPACTION",
    name: "Water Compaction",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 196,
    key: "MERCILESS",
    name: "Merciless",
    tags: [
      "ConditionalCritAbAttr"
    ],
    ignorable: false
  },
  {
    id: 197,
    key: "SHIELDS_DOWN",
    name: "Shields Down",
    tags: [
      "PostBattleInitFormChangeAbAttr",
      "PostSummonFormChangeAbAttr",
      "PostTurnFormChangeAbAttr",
      "NoFusionAbilityAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 198,
    key: "STAKEOUT",
    name: "Stakeout",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 199,
    key: "WATER_BUBBLE",
    name: "Water Bubble",
    tags: [
      "ReceivedTypeDamageMultiplierAbAttr",
      "MoveTypePowerBoostAbAttr",
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 200,
    key: "STEELWORKER",
    name: "Steelworker",
    tags: [
      "MoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 201,
    key: "BERSERK",
    name: "Berserk",
    tags: [
      "PostDefendHpGatedStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 202,
    key: "SLUSH_RUSH",
    name: "Slush Rush",
    tags: [
      "StatMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 203,
    key: "LONG_REACH",
    name: "Long Reach",
    tags: [
      "IgnoreContactAbAttr"
    ],
    ignorable: false
  },
  {
    id: 204,
    key: "LIQUID_VOICE",
    name: "Liquid Voice",
    tags: [
      "MoveTypeChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 205,
    key: "TRIAGE",
    name: "Triage",
    tags: [
      "ChangeMovePriorityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 206,
    key: "GALVANIZE",
    name: "Galvanize",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 207,
    key: "SURGE_SURFER",
    name: "Surge Surfer",
    tags: [],
    ignorable: false
  },
  {
    id: 208,
    key: "SCHOOLING",
    name: "Schooling",
    tags: [
      "PostBattleInitFormChangeAbAttr",
      "PostSummonFormChangeAbAttr",
      "PostTurnFormChangeAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 209,
    key: "DISGUISE",
    name: "Disguise",
    tags: [
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr",
      "FormBlockDamageAbAttr",
      "PostBattleInitFormChangeAbAttr",
      "PostFaintFormChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 210,
    key: "BATTLE_BOND",
    name: "Battle Bond",
    tags: [],
    ignorable: false
  },
  {
    id: 211,
    key: "POWER_CONSTRUCT",
    name: "Power Construct",
    tags: [
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 212,
    key: "CORROSION",
    name: "Corrosion",
    tags: [
      "IgnoreTypeStatusEffectImmunityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 213,
    key: "COMATOSE",
    name: "Comatose",
    tags: [
      "StatusEffectImmunityAbAttr",
      "BattlerTagImmunityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 214,
    key: "QUEENLY_MAJESTY",
    name: "Queenly Majesty",
    tags: [
      "FieldPriorityMoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 215,
    key: "INNARDS_OUT",
    name: "Innards Out",
    tags: [
      "PostFaintHPDamageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 216,
    key: "DANCER",
    name: "Dancer",
    tags: [
      "PostDancingMoveAbAttr"
    ],
    ignorable: false
  },
  {
    id: 217,
    key: "BATTERY",
    name: "Battery",
    tags: [
      "AllyMoveCategoryPowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 218,
    key: "FLUFFY",
    name: "Fluffy",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 219,
    key: "DAZZLING",
    name: "Dazzling",
    tags: [
      "FieldPriorityMoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 220,
    key: "SOUL_HEART",
    name: "Soul Heart",
    tags: [
      "PostKnockOutStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 221,
    key: "TANGLING_HAIR",
    name: "Tangling Hair",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 222,
    key: "RECEIVER",
    name: "Receiver",
    tags: [
      "CopyFaintedAllyAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 223,
    key: "POWER_OF_ALCHEMY",
    name: "Power Of Alchemy",
    tags: [
      "CopyFaintedAllyAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 224,
    key: "BEAST_BOOST",
    name: "Beast Boost",
    tags: [
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 225,
    key: "RKS_SYSTEM",
    name: "Rks System",
    tags: [
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 226,
    key: "ELECTRIC_SURGE",
    name: "Electric Surge",
    tags: [
      "PostSummonTerrainChangeAbAttr",
      "PostBiomeChangeTerrainChangeAbAttr",
      "SummonTerrainAiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 227,
    key: "PSYCHIC_SURGE",
    name: "Psychic Surge",
    tags: [
      "PostSummonTerrainChangeAbAttr",
      "PostBiomeChangeTerrainChangeAbAttr",
      "SummonTerrainAiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 228,
    key: "MISTY_SURGE",
    name: "Misty Surge",
    tags: [
      "PostSummonTerrainChangeAbAttr",
      "PostBiomeChangeTerrainChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 229,
    key: "GRASSY_SURGE",
    name: "Grassy Surge",
    tags: [
      "PostSummonTerrainChangeAbAttr",
      "PostBiomeChangeTerrainChangeAbAttr",
      "SummonTerrainAiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 230,
    key: "FULL_METAL_BODY",
    name: "Full Metal Body",
    tags: [
      "ProtectStatAbAttr"
    ],
    ignorable: false
  },
  {
    id: 231,
    key: "SHADOW_SHIELD",
    name: "Shadow Shield",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 232,
    key: "PRISM_ARMOR",
    name: "Prism Armor",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: false
  },
  {
    id: 233,
    key: "NEUROFORCE",
    name: "Neuroforce",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 234,
    key: "INTREPID_SWORD",
    name: "Intrepid Sword",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 235,
    key: "DAUNTLESS_SHIELD",
    name: "Dauntless Shield",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 236,
    key: "LIBERO",
    name: "Libero",
    tags: [
      "PokemonTypeChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 237,
    key: "BALL_FETCH",
    name: "Ball Fetch",
    tags: [
      "FetchBallAbAttr"
    ],
    ignorable: false
  },
  {
    id: 238,
    key: "COTTON_DOWN",
    name: "Cotton Down",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 239,
    key: "PROPELLER_TAIL",
    name: "Propeller Tail",
    tags: [
      "BlockRedirectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 240,
    key: "MIRROR_ARMOR",
    name: "Mirror Armor",
    tags: [
      "ReflectStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 241,
    key: "GULP_MISSILE",
    name: "Gulp Missile",
    tags: [
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 242,
    key: "STALWART",
    name: "Stalwart",
    tags: [
      "BlockRedirectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 243,
    key: "STEAM_ENGINE",
    name: "Steam Engine",
    tags: [
      "PostDefendStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 244,
    key: "PUNK_ROCK",
    name: "Punk Rock",
    tags: [
      "MovePowerBoostAbAttr",
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 245,
    key: "SAND_SPIT",
    name: "Sand Spit",
    tags: [
      "PostDefendWeatherChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 246,
    key: "ICE_SCALES",
    name: "Ice Scales",
    tags: [
      "ReceivedMoveDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 247,
    key: "RIPEN",
    name: "Ripen",
    tags: [
      "DoubleBerryEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 248,
    key: "ICE_FACE",
    name: "Ice Face",
    tags: [
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr",
      "IceFaceFormChangeAbAttr",
      "FormBlockDamageAbAttr",
      "PostBattleInitFormChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 249,
    key: "POWER_SPOT",
    name: "Power Spot",
    tags: [
      "AllyMoveCategoryPowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 250,
    key: "MIMICRY",
    name: "Mimicry",
    tags: [
      "TerrainEventTypeChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 251,
    key: "SCREEN_CLEANER",
    name: "Screen Cleaner",
    tags: [
      "PostSummonRemoveArenaTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 252,
    key: "STEELY_SPIRIT",
    name: "Steely Spirit",
    tags: [
      "UserFieldMoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 253,
    key: "PERISH_BODY",
    name: "Perish Body",
    tags: [
      "PostDefendPerishSongAbAttr"
    ],
    ignorable: false
  },
  {
    id: 254,
    key: "WANDERING_SPIRIT",
    name: "Wandering Spirit",
    tags: [
      "PostDefendAbilitySwapAbAttr"
    ],
    ignorable: false
  },
  {
    id: 255,
    key: "GORILLA_TACTICS",
    name: "Gorilla Tactics",
    tags: [
      "GorillaTacticsAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 256,
    key: "NEUTRALIZING_GAS",
    name: "Neutralizing Gas",
    tags: [
      "PostSummonAddArenaTagAbAttr",
      "PreLeaveFieldRemoveSuppressAbilitiesSourceAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 257,
    key: "PASTEL_VEIL",
    name: "Pastel Veil",
    tags: [
      "PostSummonUserFieldRemoveStatusEffectAbAttr",
      "UserFieldStatusEffectImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 258,
    key: "HUNGER_SWITCH",
    name: "Hunger Switch",
    tags: [
      "PostTurnFormChangeAbAttr",
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 259,
    key: "QUICK_DRAW",
    name: "Quick Draw",
    tags: [
      "BypassSpeedChanceAbAttr"
    ],
    ignorable: false
  },
  {
    id: 260,
    key: "UNSEEN_FIST",
    name: "Unseen Fist",
    tags: [
      "IgnoreProtectOnContactAbAttr",
      "MoveDamageBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 261,
    key: "CURIOUS_MEDICINE",
    name: "Curious Medicine",
    tags: [
      "PostSummonClearAllyStatStagesAbAttr"
    ],
    ignorable: false
  },
  {
    id: 262,
    key: "TRANSISTOR",
    name: "Transistor",
    tags: [
      "MoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 263,
    key: "DRAGONS_MAW",
    name: "Dragons Maw",
    tags: [
      "MoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 264,
    key: "CHILLING_NEIGH",
    name: "Chilling Neigh",
    tags: [
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 265,
    key: "GRIM_NEIGH",
    name: "Grim Neigh",
    tags: [
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 266,
    key: "AS_ONE_GLASTRIER",
    name: "As One Glastrier",
    tags: [
      "PostSummonMessageAbAttr",
      "PreventBerryUseAbAttr",
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 267,
    key: "AS_ONE_SPECTRIER",
    name: "As One Spectrier",
    tags: [
      "PostSummonMessageAbAttr",
      "PreventBerryUseAbAttr",
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 268,
    key: "LINGERING_AROMA",
    name: "Lingering Aroma",
    tags: [
      "PostDefendAbilityGiveAbAttr"
    ],
    ignorable: false
  },
  {
    id: 269,
    key: "SEED_SOWER",
    name: "Seed Sower",
    tags: [
      "PostDefendTerrainChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 270,
    key: "THERMAL_EXCHANGE",
    name: "Thermal Exchange",
    tags: [
      "PostDefendStatStageChangeAbAttr",
      "StatusEffectImmunityAbAttr",
      "PostSummonHealStatusAbAttr"
    ],
    ignorable: true
  },
  {
    id: 271,
    key: "ANGER_SHELL",
    name: "Anger Shell",
    tags: [
      "PostDefendHpGatedStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 272,
    key: "PURIFYING_SALT",
    name: "Purifying Salt",
    tags: [
      "StatusEffectImmunityAbAttr",
      "ReceivedTypeDamageMultiplierAbAttr"
    ],
    ignorable: true
  },
  {
    id: 273,
    key: "WELL_BAKED_BODY",
    name: "Well Baked Body",
    tags: [
      "TypeImmunityStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 274,
    key: "WIND_RIDER",
    name: "Wind Rider",
    tags: [
      "MoveImmunityStatStageChangeAbAttr",
      "PostSummonStatStageChangeOnArenaAbAttr"
    ],
    ignorable: true
  },
  {
    id: 275,
    key: "GUARD_DOG",
    name: "Guard Dog",
    tags: [
      "PostIntimidateStatStageChangeAbAttr",
      "ForceSwitchOutImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 276,
    key: "ROCKY_PAYLOAD",
    name: "Rocky Payload",
    tags: [
      "MoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 277,
    key: "WIND_POWER",
    name: "Wind Power",
    tags: [
      "PostDefendApplyBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 278,
    key: "ZERO_TO_HERO",
    name: "Zero To Hero",
    tags: [
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr",
      "PostBattleInitFormChangeAbAttr",
      "PreSwitchOutFormChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 279,
    key: "COMMANDER",
    name: "Commander",
    tags: [
      "CommanderAbAttr",
      "DoubleBattleChanceAbAttr"
    ],
    ignorable: false
  },
  {
    id: 280,
    key: "ELECTROMORPHOSIS",
    name: "Electromorphosis",
    tags: [
      "PostDefendApplyBattlerTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 281,
    key: "PROTOSYNTHESIS",
    name: "Protosynthesis",
    tags: [
      "PostWeatherChangeAddBattlerTagAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 282,
    key: "QUARK_DRIVE",
    name: "Quark Drive",
    tags: [
      "PostTerrainChangeAddBattlerTagAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 283,
    key: "GOOD_AS_GOLD",
    name: "Good As Gold",
    tags: [
      "MoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 284,
    key: "VESSEL_OF_RUIN",
    name: "Vessel Of Ruin",
    tags: [
      "FieldMultiplyStatAbAttr",
      "PostSummonMessageAbAttr"
    ],
    ignorable: true
  },
  {
    id: 285,
    key: "SWORD_OF_RUIN",
    name: "Sword Of Ruin",
    tags: [
      "FieldMultiplyStatAbAttr",
      "AiMovegenMoveStatsAbAttr",
      "PostSummonMessageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 286,
    key: "TABLETS_OF_RUIN",
    name: "Tablets Of Ruin",
    tags: [
      "FieldMultiplyStatAbAttr",
      "PostSummonMessageAbAttr"
    ],
    ignorable: true
  },
  {
    id: 287,
    key: "BEADS_OF_RUIN",
    name: "Beads Of Ruin",
    tags: [
      "FieldMultiplyStatAbAttr",
      "AiMovegenMoveStatsAbAttr",
      "PostSummonMessageAbAttr"
    ],
    ignorable: false
  },
  {
    id: 288,
    key: "ORICHALCUM_PULSE",
    name: "Orichalcum Pulse",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostBiomeChangeWeatherChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 289,
    key: "HADRON_ENGINE",
    name: "Hadron Engine",
    tags: [
      "PostSummonTerrainChangeAbAttr",
      "PostBiomeChangeTerrainChangeAbAttr",
      "AiMovegenMoveStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 290,
    key: "OPPORTUNIST",
    name: "Opportunist",
    tags: [
      "StatStageChangeCopyAbAttr"
    ],
    ignorable: false
  },
  {
    id: 291,
    key: "CUD_CHEW",
    name: "Cud Chew",
    tags: [
      "CudChewConsumeBerryAbAttr",
      "CudChewRecordBerryAbAttr"
    ],
    ignorable: false
  },
  {
    id: 292,
    key: "SHARPNESS",
    name: "Sharpness",
    tags: [
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 293,
    key: "SUPREME_OVERLORD",
    name: "Supreme Overlord",
    tags: [],
    ignorable: false
  },
  {
    id: 294,
    key: "COSTAR",
    name: "Costar",
    tags: [
      "PostSummonCopyAllyStatsAbAttr"
    ],
    ignorable: false
  },
  {
    id: 295,
    key: "TOXIC_DEBRIS",
    name: "Toxic Debris",
    tags: [
      "PostDefendApplyArenaTrapTagAbAttr"
    ],
    ignorable: false
  },
  {
    id: 296,
    key: "ARMOR_TAIL",
    name: "Armor Tail",
    tags: [
      "FieldPriorityMoveImmunityAbAttr"
    ],
    ignorable: true
  },
  {
    id: 297,
    key: "EARTH_EATER",
    name: "Earth Eater",
    tags: [
      "TypeImmunityHealAbAttr"
    ],
    ignorable: true
  },
  {
    id: 298,
    key: "MYCELIUM_MIGHT",
    name: "Mycelium Might",
    tags: [
      "ChangeMovePriorityInBracketAbAttr",
      "PreventBypassSpeedChanceAbAttr",
      "MoveAbilityBypassAbAttr"
    ],
    ignorable: false
  },
  {
    id: 299,
    key: "MINDS_EYE",
    name: "Minds Eye",
    tags: [
      "IgnoreTypeImmunityAbAttr",
      "ProtectStatAbAttr",
      "IgnoreOpponentStatStagesAbAttr"
    ],
    ignorable: true
  },
  {
    id: 300,
    key: "SUPERSWEET_SYRUP",
    name: "Supersweet Syrup",
    tags: [
      "PostSummonStatStageChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 301,
    key: "HOSPITALITY",
    name: "Hospitality",
    tags: [
      "PostSummonAllyHealAbAttr"
    ],
    ignorable: false
  },
  {
    id: 302,
    key: "TOXIC_CHAIN",
    name: "Toxic Chain",
    tags: [
      "PostAttackApplyStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 303,
    key: "EMBODY_ASPECT_TEAL",
    name: "Embody Aspect Teal",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 304,
    key: "EMBODY_ASPECT_WELLSPRING",
    name: "Embody Aspect Wellspring",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 305,
    key: "EMBODY_ASPECT_HEARTHFLAME",
    name: "Embody Aspect Hearthflame",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 306,
    key: "EMBODY_ASPECT_CORNERSTONE",
    name: "Embody Aspect Cornerstone",
    tags: [
      "PostSummonStatStageChangeAbAttr",
      "NoTransformAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 307,
    key: "TERA_SHIFT",
    name: "Tera Shift",
    tags: [
      "PostSummonFormChangeAbAttr",
      "NoTransformAbilityAbAttr",
      "NoFusionAbilityAbAttr"
    ],
    ignorable: false
  },
  {
    id: 308,
    key: "TERA_SHELL",
    name: "Tera Shell",
    tags: [
      "FullHpResistTypeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 309,
    key: "TERAFORM_ZERO",
    name: "Teraform Zero",
    tags: [
      "PostSummonWeatherChangeAbAttr",
      "PostSummonTerrainChangeAbAttr"
    ],
    ignorable: false
  },
  {
    id: 310,
    key: "POISON_PUPPETEER",
    name: "Poison Puppeteer",
    tags: [
      "ConfusionOnStatusEffectAbAttr"
    ],
    ignorable: false
  },
  {
    id: 311,
    key: "PIERCING_DRILL",
    name: "Piercing Drill",
    tags: [
      "IgnoreProtectOnContactAbAttr",
      "MoveDamageBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 312,
    key: "DRAGONIZE",
    name: "Dragonize",
    tags: [
      "MoveTypeChangeAbAttr",
      "MovePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 313,
    key: "EELEVATE",
    name: "Eelevate",
    tags: [
      "AttackTypeImmunityAbAttr",
      "PostVictoryStatStageChangeAbAttr"
    ],
    ignorable: true
  },
  {
    id: 314,
    key: "ABILITY_314",
    name: "Ability 314",
    tags: [],
    ignorable: false
  },
  {
    id: 315,
    key: "MEGA_SOL",
    name: "Mega Sol",
    tags: [
      "PreAttackWeatherOverrideAbAttr"
    ],
    ignorable: false
  },
  {
    id: 316,
    key: "FIRE_MANE",
    name: "Fire Mane",
    tags: [
      "MoveTypePowerBoostAbAttr"
    ],
    ignorable: false
  },
  {
    id: 317,
    key: "ABILITY_317",
    name: "Ability 317",
    tags: [],
    ignorable: false
  },
  {
    id: 318,
    key: "SPICY_SPRAY",
    name: "Spicy Spray",
    tags: [
      "PostDefendApplyStatusEffectAbAttr"
    ],
    ignorable: false
  }
];

